/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LiaoActionsPlugin: typeof import('./src/components/LiaoPlugins/LiaoActionsPlugin.vue')['default']
    LiaoApp: typeof import('./src/components/LiaoApp/LiaoApp.vue')['default']
    LiaoButton: typeof import('./src/components/LiaoButton/LiaoButton.vue')['default']
    LiaoEmojiPicker: typeof import('./src/components/LiaoEmojiPicker/LiaoEmojiPicker.vue')['default']
    LiaoFaqCardPlugin: typeof import('./src/components/LiaoPlugins/LiaoFaqCardPlugin.vue')['default']
    LiaoFileBubble: typeof import('./src/components/LiaoMessageBubble/LiaoFileBubble.vue')['default']
    LiaoFileChipList: typeof import('./src/components/LiaoFileChipList/LiaoFileChipList.vue')['default']
    LiaoFilePreview: typeof import('./src/components/LiaoFilePreview/LiaoFilePreview.vue')['default']
    LiaoFileUpload: typeof import('./src/components/LiaoFileUpload/LiaoFileUpload.vue')['default']
    LiaoFormPlugin: typeof import('./src/components/LiaoPlugins/LiaoFormPlugin.vue')['default']
    LiaoIcon: typeof import('./src/components/LiaoIcon/LiaoIcon.vue')['default']
    LiaoImageBubble: typeof import('./src/components/LiaoMessageBubble/LiaoImageBubble.vue')['default']
    LiaoImageCardPlugin: typeof import('./src/components/LiaoPlugins/LiaoImageCardPlugin.vue')['default']
    LiaoInfoPlugin: typeof import('./src/components/LiaoPlugins/LiaoInfoPlugin.vue')['default']
    LiaoInputArea: typeof import('./src/components/LiaoInputArea/LiaoInputArea.vue')['default']
    LiaoListPlugin: typeof import('./src/components/LiaoPlugins/LiaoListPlugin.vue')['default']
    LiaoMediaCarouselPlugin: typeof import('./src/components/LiaoPlugins/LiaoMediaCarouselPlugin.vue')['default']
    LiaoMessageBubble: typeof import('./src/components/LiaoMessageBubble/LiaoMessageBubble.vue')['default']
    LiaoMessageList: typeof import('./src/components/LiaoMessageList/LiaoMessageList.vue')['default']
    LiaoPluginBubble: typeof import('./src/components/LiaoMessageBubble/LiaoPluginBubble.vue')['default']
    LiaoPluginDebugger: typeof import('./src/components/LiaoPlugins/LiaoPluginDebugger.vue')['default']
    LiaoProgressPlugin: typeof import('./src/components/LiaoPlugins/LiaoProgressPlugin.vue')['default']
    LiaoQuickActionBar: typeof import('./src/components/LiaoQuickActionBar/LiaoQuickActionBar.vue')['default']
    LiaoStatsPlugin: typeof import('./src/components/LiaoPlugins/LiaoStatsPlugin.vue')['default']
    LiaoTextBubble: typeof import('./src/components/LiaoMessageBubble/LiaoTextBubble.vue')['default']
    LiaoTimelinePlugin: typeof import('./src/components/LiaoPlugins/LiaoTimelinePlugin.vue')['default']
    LiaoVotePlugin: typeof import('./src/components/LiaoPlugins/LiaoVotePlugin.vue')['default']
    LiaoWindow: typeof import('./src/components/LiaoWindow/LiaoWindow.vue')['default']
    LiaoWindowHeader: typeof import('./src/components/LiaoWindowHeader/LiaoWindowHeader.vue')['default']
    LiaoWindowList: typeof import('./src/components/LiaoWindowList/LiaoWindowList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
